apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cliconfigs.netclab.dev
spec:
  compositeTypeRef:
    apiVersion: netclab.dev/v1alpha1
    kind: CliConfig
  mode: Pipeline
  pipeline:
  - step: environmentConfigs
    functionRef:
      name: crossplane-contrib-function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: endpoint-protocols

  - step: requests
    functionRef:
      name: netclab-function-eapi
    requirements:
      requiredResources:
      - requirementName: eos-creds
        apiVersion: v1
        kind: Secret
        name: eos-creds
        namespace: crossplane-system

  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
